# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_autotest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u6d4b\u8bd5ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u7528\u6237\u540d')),
            ],
        ),
    ]
