# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-12 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='\u670d\u52a1\u5668ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP\u5730\u5740')),
                ('port', models.IntegerField(verbose_name='\u7aef\u53e3')),
                ('username', models.CharField(max_length=128, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=128, verbose_name='\u5bc6\u7801')),
                ('protocal', models.CharField(choices=[('SSH', 'SSH'), ('RDP', 'RDP')], max_length=10, verbose_name='\u8fdc\u7a0b\u8fde\u63a5\u7c7b\u578b')),
                ('isdelete', models.CharField(default='N', max_length=4, verbose_name='\u662f\u5426\u5220\u9664')),
                ('current_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerDetail',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='\u4fe1\u606f\u7f16\u53f7ID')),
                ('server_id', models.IntegerField(verbose_name='\u670d\u52a1\u5668ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP\u5730\u5740')),
                ('port', models.IntegerField(verbose_name='\u7aef\u53e3')),
                ('os_info', models.CharField(max_length=128, verbose_name='\u64cd\u4f5c\u7cfb\u7edf\u4fe1\u606f')),
                ('cpu_info', models.CharField(max_length=128, verbose_name='CPU\u4fe1\u606f')),
                ('cpu_count', models.IntegerField(verbose_name='CPU\u4e2a\u6570')),
                ('mem_info', models.CharField(max_length=20, verbose_name='\u5185\u5b58\u5927\u5c0f')),
                ('disk_info', models.CharField(max_length=20, verbose_name='\u786c\u76d8\u5927\u5c0f')),
                ('isdelete', models.CharField(default='N', max_length=4, verbose_name='\u662f\u5426\u5220\u9664')),
                ('current_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='\u7528\u6237ID')),
                ('username', models.CharField(max_length=128, unique=True, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=128, verbose_name='\u5bc6\u7801')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
                ('phone', models.CharField(max_length=20, verbose_name='\u7535\u8bdd')),
                ('isdelete', models.CharField(default='N', max_length=4, verbose_name='\u662f\u5426\u5220\u9664')),
                ('current_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserServer',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='\u4fe1\u606f\u7f16\u53f7ID')),
                ('user_id', models.IntegerField(verbose_name='\u7528\u6237ID')),
                ('username', models.CharField(max_length=128, unique=True, verbose_name='\u7528\u6237\u540d')),
                ('server_id', models.IntegerField(verbose_name='\u670d\u52a1\u5668ID')),
                ('server_ip', models.GenericIPAddressField(verbose_name='IP\u5730\u5740')),
                ('isdelete', models.CharField(default='N', max_length=4, verbose_name='\u662f\u5426\u5220\u9664')),
                ('current_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
