# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clocmdb', '0003_sendcodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.IntegerField(verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u59d3\u540d')),
            ],
        ),
    ]
