# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_flag', models.CharField(max_length=10, verbose_name='\u662f\u5426\u88ab\u5220\u9664')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Base')),
                ('groupname', models.CharField(max_length=128, verbose_name='\u7ec4\u540d\u79f0')),
                ('description', models.TextField(verbose_name='\u7ec4\u63cf\u8ff0')),
            ],
            bases=('users.base',),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Base')),
                ('groupname', models.CharField(max_length=128, verbose_name='\u6743\u9650\u540d\u79f0')),
                ('description', models.TextField(verbose_name='\u6743\u9650\u63cf\u8ff0')),
            ],
            bases=('users.base',),
        ),
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Base')),
                ('group_id', models.IntegerField(verbose_name='\u7ec4ID')),
                ('permission_id', models.IntegerField(verbose_name='\u6743\u9650ID')),
            ],
            bases=('users.base',),
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Base')),
                ('ip', models.GenericIPAddressField(verbose_name='IP\u5730\u5740')),
                ('port', models.IntegerField(verbose_name='\u7aef\u53e3')),
                ('username', models.CharField(max_length=128, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=128, verbose_name='\u5bc6\u7801')),
                ('protocal', models.CharField(choices=[('SSH', 'SSH'), ('RDP', 'RDP')], max_length=10, verbose_name='\u8fdc\u7a0b\u8fde\u63a5\u7c7b\u578b')),
                ('isActive', models.CharField(choices=[('Y', '\u6fc0\u6d3b'), ('N', '\u672a\u6fc0\u6d3b')], max_length=2, verbose_name='\u662f\u5426\u6fc0\u6d3b')),
            ],
            bases=('users.base',),
        ),
        migrations.CreateModel(
            name='ServerDetail',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Base')),
                ('server_id', models.IntegerField(verbose_name='\u670d\u52a1\u5668ID')),
                ('os_info', models.CharField(max_length=128, verbose_name='\u64cd\u4f5c\u7cfb\u7edf\u4fe1\u606f')),
                ('cpu_info', models.CharField(max_length=128, verbose_name='CPU\u4fe1\u606f')),
                ('cpu_count', models.IntegerField(verbose_name='CPU\u4e2a\u6570')),
                ('mem_info', models.CharField(max_length=20, verbose_name='\u5185\u5b58\u5927\u5c0f')),
                ('disk_info', models.CharField(max_length=20, verbose_name='\u786c\u76d8\u5927\u5c0f')),
            ],
            bases=('users.base',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Base')),
                ('username', models.CharField(max_length=128, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=128, verbose_name='\u5bc6\u7801')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
                ('phone', models.IntegerField(verbose_name='\u7535\u8bdd')),
            ],
            bases=('users.base',),
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Base')),
                ('user_id', models.IntegerField(verbose_name='\u7528\u6237ID')),
                ('group_id', models.IntegerField(verbose_name='\u7ec4ID')),
            ],
            bases=('users.base',),
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Base')),
                ('user_id', models.IntegerField(verbose_name='\u7528\u6237ID')),
                ('permission_id', models.IntegerField(verbose_name='\u6743\u9650ID')),
            ],
            bases=('users.base',),
        ),
        migrations.CreateModel(
            name='UserServer',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Base')),
                ('user_id', models.IntegerField(verbose_name='\u7528\u6237ID')),
                ('server_id', models.IntegerField(verbose_name='\u670d\u52a1\u5668ID')),
            ],
            bases=('users.base',),
        ),
    ]
