# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_test1'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPUstat',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Base')),
                ('cpu_percent', models.CharField(max_length=10, verbose_name='CPU\u4f7f\u7528\u7387')),
                ('curr_time', models.CharField(max_length=128, verbose_name='\u5f53\u524d\u65f6\u95f4')),
            ],
            bases=('users.base',),
        ),
    ]
