# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_cpustat'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPUstat2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_percent', models.CharField(max_length=10, verbose_name='CPU\u4f7f\u7528\u7387')),
                ('curr_time', models.CharField(max_length=128, verbose_name='\u5f53\u524d\u65f6\u95f4')),
            ],
        ),
    ]
