# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_sendcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendCodes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, verbose_name='\u7528\u6237\u540d')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
                ('emailcode', models.CharField(max_length=20, verbose_name='\u90ae\u7bb1\u9a8c\u8bc1\u7801')),
                ('current_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
