# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=128, verbose_name='\u4e3b\u673a\u540d')),
                ('ip', models.GenericIPAddressField(verbose_name='IP\u5730\u5740')),
                ('manager', models.CharField(max_length=128, verbose_name='\u8054\u7cfb\u4eba')),
                ('phone', models.IntegerField(verbose_name='\u7535\u8bdd\u53f7\u7801')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
            ],
        ),
    ]
