# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u4e66\u540d')),
                ('publish_date', models.DateField(verbose_name='\u51fa\u7248\u65e5\u671f')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='\u51fa\u7248\u793e\u540d\u79f0')),
                ('address', models.CharField(max_length=128, verbose_name='\u51fa\u7248\u793e\u5730\u5740')),
                ('city', models.CharField(max_length=128, verbose_name='\u51fa\u7248\u793e\u57ce\u5e02')),
                ('country', models.CharField(max_length=128, verbose_name='\u51fa\u7248\u793e\u56fd\u5bb6')),
                ('website', models.URLField(max_length=64, verbose_name='\u51fa\u7248\u793e\u7f51\u5740')),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=128, verbose_name='\u4f5c\u8005'),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='app01.Author', verbose_name='\u4f5c\u8005'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Publisher', verbose_name='\u51fa\u7248\u793e\u540d\u79f0'),
        ),
    ]
